version: '3.8'

services:
  nest-app:
    build: .
    working_dir: /app
    command: npm run start:dev
    env_file:
      - '.env.dev'
    ports:
      - "3000:3000"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    env_file:
      - '.env.dev'
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
