export const survey_data = [
  {
    id: 1,
    title: '너는 뭘 좋아해?',
    description: '좋아하는 것에 대한 설문 조사입니다.',
    max_participants: 100,
    now_participants: 0,
    question_id: 1,
    question_title: '가장 좋아하는 색깔은?',
    question_order: 1,
    choice_id: 1,
    choice_content: '빨강',
    choice_order: '빨강',
  },
  {
    id: 1,
    title: '너는 뭘 좋아해?',
    description: '좋아하는 것에 대한 설문 조사입니다.',
    max_participants: 100,
    now_participants: 0,
    question_id: 1,
    question_title: '가장 좋아하는 색깔은?',
    question_order: 1,
    choice_id: 2,
    choice_content: '파랑',
    choice_order: '파랑',
  },
  {
    id: 1,
    title: '너는 뭘 좋아해?',
    description: '좋아하는 것에 대한 설문 조사입니다.',
    max_participants: 100,
    now_participants: 0,
    question_id: 1,
    question_title: '가장 좋아하는 색깔은?',
    question_order: 1,
    choice_id: 3,
    choice_content: '노랑',
    choice_order: '노랑',
  },
  {
    id: 1,
    title: '너는 뭘 좋아해?',
    description: '좋아하는 것에 대한 설문 조사입니다.',
    max_participants: 100,
    now_participants: 0,
    question_id: 1,
    question_title: '가장 좋아하는 색깔은?',
    question_order: 1,
    choice_id: 4,
    choice_content: '주황',
    choice_order: '주황',
  },
  {
    id: 1,
    title: '너는 뭘 좋아해?',
    description: '좋아하는 것에 대한 설문 조사입니다.',
    max_participants: 100,
    now_participants: 0,
    question_id: 2,
    question_title: '가장 좋아하는 음식은?',
    question_order: 2,
    choice_id: 5,
    choice_content: '피자',
    choice_order: '피자',
  },
  {
    id: 1,
    title: '너는 뭘 좋아해?',
    description: '좋아하는 것에 대한 설문 조사입니다.',
    max_participants: 100,
    now_participants: 0,
    question_id: 2,
    question_title: '가장 좋아하는 음식은?',
    question_order: 2,
    choice_id: 6,
    choice_content: '치킨',
    choice_order: '치킨',
  },
  {
    id: 1,
    title: '너는 뭘 좋아해?',
    description: '좋아하는 것에 대한 설문 조사입니다.',
    max_participants: 100,
    now_participants: 0,
    question_id: 2,
    question_title: '가장 좋아하는 음식은?',
    question_order: 2,
    choice_id: 7,
    choice_content: '잔치국수',
    choice_order: '잔치국수',
  },
  {
    id: 1,
    title: '너는 뭘 좋아해?',
    description: '좋아하는 것에 대한 설문 조사입니다.',
    max_participants: 100,
    now_participants: 0,
    question_id: 2,
    question_title: '가장 좋아하는 음식은?',
    question_order: 2,
    choice_id: 8,
    choice_content: '오삼불고기',
    choice_order: '오삼불고기',
  },
  {
    id: 1,
    title: '너는 뭘 좋아해?',
    description: '좋아하는 것에 대한 설문 조사입니다.',
    max_participants: 100,
    now_participants: 0,
    question_id: 3,
    question_title: '흡연 중이십니까?',
    question_order: 3,
    choice_id: 9,
    choice_content: '예',
    choice_order: '예',
  },
  {
    id: 1,
    title: '너는 뭘 좋아해?',
    description: '좋아하는 것에 대한 설문 조사입니다.',
    max_participants: 100,
    now_participants: 0,
    question_id: 3,
    question_title: '흡연 중이십니까?',
    question_order: 3,
    choice_id: 10,
    choice_content: '아니오',
    choice_order: '아니오',
  },
  {
    id: 1,
    title: '너는 뭘 좋아해?',
    description: '좋아하는 것에 대한 설문 조사입니다.',
    max_participants: 100,
    now_participants: 0,
    question_id: 4,
    question_title: '어느 정도 피시나요?',
    question_order: 4,
    choice_id: 11,
    choice_content: '하루 한 갑',
    choice_order: '하루 한 갑',
  },
  {
    id: 1,
    title: '너는 뭘 좋아해?',
    description: '좋아하는 것에 대한 설문 조사입니다.',
    max_participants: 100,
    now_participants: 0,
    question_id: 4,
    question_title: '어느 정도 피시나요?',
    question_order: 4,
    choice_id: 12,
    choice_content: '일주일 한 갑',
    choice_order: '일주일 한 갑',
  },
  {
    id: 1,
    title: '너는 뭘 좋아해?',
    description: '좋아하는 것에 대한 설문 조사입니다.',
    max_participants: 100,
    now_participants: 0,
    question_id: 4,
    question_title: '어느 정도 피시나요?',
    question_order: 4,
    choice_id: 13,
    choice_content: '한 달 한 갑',
    choice_order: '한 달 한 갑',
  },
  {
    id: 1,
    title: '너는 뭘 좋아해?',
    description: '좋아하는 것에 대한 설문 조사입니다.',
    max_participants: 100,
    now_participants: 0,
    question_id: 5,
    question_title: '운동하나요?',
    question_order: 5,
    choice_id: 14,
    choice_content: '예',
    choice_order: '예',
  },
  {
    id: 1,
    title: '너는 뭘 좋아해?',
    description: '좋아하는 것에 대한 설문 조사입니다.',
    max_participants: 100,
    now_participants: 0,
    question_id: 5,
    question_title: '운동하나요?',
    question_order: 5,
    choice_id: 15,
    choice_content: '아니오',
    choice_order: '아니오',
  },
  {
    id: 1,
    title: '너는 뭘 좋아해?',
    description: '좋아하는 것에 대한 설문 조사입니다.',
    max_participants: 100,
    now_participants: 0,
    question_id: 6,
    question_title: '얼마나 자주하나요?',
    question_order: 6,
    choice_id: 16,
    choice_content: '일주일 1회',
    choice_order: '일주일 1회',
  },
  {
    id: 1,
    title: '너는 뭘 좋아해?',
    description: '좋아하는 것에 대한 설문 조사입니다.',
    max_participants: 100,
    now_participants: 0,
    question_id: 6,
    question_title: '얼마나 자주하나요?',
    question_order: 6,
    choice_id: 17,
    choice_content: '일주일 2회',
    choice_order: '일주일 2회',
  },
  {
    id: 1,
    title: '너는 뭘 좋아해?',
    description: '좋아하는 것에 대한 설문 조사입니다.',
    max_participants: 100,
    now_participants: 0,
    question_id: 6,
    question_title: '얼마나 자주하나요?',
    question_order: 6,
    choice_id: 18,
    choice_content: '일주일 3회',
    choice_order: '일주일 3회',
  },
  {
    id: 1,
    title: '너는 뭘 좋아해?',
    description: '좋아하는 것에 대한 설문 조사입니다.',
    max_participants: 100,
    now_participants: 0,
    question_id: 7,
    question_title: '몸 상태가 어떤가요?',
    question_order: 7,
    choice_id: 19,
    choice_content: '안좋음',
    choice_order: '안좋음',
  },
  {
    id: 1,
    title: '너는 뭘 좋아해?',
    description: '좋아하는 것에 대한 설문 조사입니다.',
    max_participants: 100,
    now_participants: 0,
    question_id: 7,
    question_title: '몸 상태가 어떤가요?',
    question_order: 7,
    choice_id: 20,
    choice_content: '보통',
    choice_order: '보통',
  },
  {
    id: 1,
    title: '너는 뭘 좋아해?',
    description: '좋아하는 것에 대한 설문 조사입니다.',
    max_participants: 100,
    now_participants: 0,
    question_id: 7,
    question_title: '몸 상태가 어떤가요?',
    question_order: 7,
    choice_id: 21,
    choice_content: '좋음',
    choice_order: '좋음',
  },
  {
    id: 1,
    title: '너는 뭘 좋아해?',
    description: '좋아하는 것에 대한 설문 조사입니다.',
    max_participants: 100,
    now_participants: 0,
    question_id: 7,
    question_title: '몸 상태가 어떤가요?',
    question_order: 7,
    choice_id: 22,
    choice_content: '매우 좋음',
    choice_order: '매우 좋음',
  },
];

export const conditional_choice_data = [
  {
    id: 1,
    survey_id: 1,
    target_question: 3,
    specific_choice: 2,
    next_question: 5,
  },
  {
    id: 2,
    survey_id: 1,
    target_question: 5,
    specific_choice: 2,
    next_question: 7,
  },
];

export const successReadSurvey = {
  id: 1,
  title: '너는 뭘 좋아해?',
  description: '좋아하는 것에 대한 설문 조사입니다.',
  max_participants: 100,
  now_participants: 0,
  questions: [
    {
      id: 1,
      title: '가장 좋아하는 색깔은?',
      order: 1,
      choices: [
        {
          id: 1,
          content: '빨강',
          order: '빨강',
        },
        {
          id: 2,
          content: '파랑',
          order: '파랑',
        },
        {
          id: 3,
          content: '노랑',
          order: '노랑',
        },
        {
          id: 4,
          content: '주황',
          order: '주황',
        },
      ],
    },
    {
      id: 2,
      title: '가장 좋아하는 음식은?',
      order: 2,
      choices: [
        {
          id: 5,
          content: '피자',
          order: '피자',
        },
        {
          id: 6,
          content: '치킨',
          order: '치킨',
        },
        {
          id: 7,
          content: '잔치국수',
          order: '잔치국수',
        },
        {
          id: 8,
          content: '오삼불고기',
          order: '오삼불고기',
        },
      ],
    },
    {
      id: 3,
      title: '흡연 중이십니까?',
      order: 3,
      choices: [
        {
          id: 9,
          content: '예',
          order: '예',
        },
        {
          id: 10,
          content: '아니오',
          order: '아니오',
        },
      ],
    },
    {
      id: 4,
      title: '어느 정도 피시나요?',
      order: 4,
      choices: [
        {
          id: 11,
          content: '하루 한 갑',
          order: '하루 한 갑',
        },
        {
          id: 12,
          content: '일주일 한 갑',
          order: '일주일 한 갑',
        },
        {
          id: 13,
          content: '한 달 한 갑',
          order: '한 달 한 갑',
        },
      ],
    },
    {
      id: 5,
      title: '운동하나요?',
      order: 5,
      choices: [
        {
          id: 14,
          content: '예',
          order: '예',
        },
        {
          id: 15,
          content: '아니오',
          order: '아니오',
        },
      ],
    },
    {
      id: 6,
      title: '얼마나 자주하나요?',
      order: 6,
      choices: [
        {
          id: 16,
          content: '일주일 1회',
          order: '일주일 1회',
        },
        {
          id: 17,
          content: '일주일 2회',
          order: '일주일 2회',
        },
        {
          id: 18,
          content: '일주일 3회',
          order: '일주일 3회',
        },
      ],
    },
    {
      id: 7,
      title: '몸 상태가 어떤가요?',
      order: 7,
      choices: [
        {
          id: 19,
          content: '안좋음',
          order: '안좋음',
        },
        {
          id: 20,
          content: '보통',
          order: '보통',
        },
        {
          id: 21,
          content: '좋음',
          order: '좋음',
        },
        {
          id: 22,
          content: '매우 좋음',
          order: '매우 좋음',
        },
      ],
    },
  ],
  conditional_choice: [
    {
      id: 1,
      target_question: 3,
      specific_choice: 2,
      next_question: 5,
    },
    {
      id: 2,
      target_question: 5,
      specific_choice: 2,
      next_question: 7,
    },
  ],
};
